### ISSUE TITLE
How do I use flags properly? Or matcher (probably)?

### ISSUE THREAD

**Issue by dwisiswant0** [scorpionknifes/go-pcre#6]
Hi there, I'm trying to use this package as an alternative to the built-in regexp if it can't compile a pattern list.

I have this pattern: `([^*\s\w,.\/?+-]\s*)?(?<![a-mo-z]\s)(?<![a-z\/_@])(\s*return\s*)?(?:alert|inputbox|showmod(?:al|eless)dialog|showhelp|infinity|isnan|isnull|iterator|msgbox|executeglobal|expression|prompt|write(?:ln)?|confirm|dialog|urn|(?:un)?eval|exec|execscript|tostring|status|execute|window|unescape|navigate|jquery|getscript|extend|prototype)(?(1)[^\w%"]|(?:\s*[^@\s\w%",.:\/+\-]))`.
My string to match are `/?query="autofocus ' onfocus='alert(document.domain)'""`.

Code:
```go
package main

import "github.com/scorpionknifes/go-pcre"

func main() {
	regex, err := pcre.Compile(`([^*\s\w,.\/?+-]\s*)?(?<![a-mo-z]\s)(?<![a-z\/_@])(\s*return\s*)?(?:alert|inputbox|showmod(?:al|eless)dialog|showhelp|infinity|isnan|isnull|iterator|msgbox|executeglobal|expression|prompt|write(?:ln)?|confirm|dialog|urn|(?:un)?eval|exec|execscript|tostring|status|execute|window|unescape|navigate|jquery|getscript|extend|prototype)(?(1)[^\w%"]|(?:\s*[^@\s\w%",.:\/+\-]))`, pcre.MULTILINE)
	if err != nil {
		panic(err)
	}

	pattern := regex.NewMatcher()
	string := `/?query="autofocus ' onfocus='alert(document.domain)'""`

	println(pattern.MatchString(string, pcre.MULTILINE))
	// Output: false
}
```

The output is **false**, and I expect it to be **true**. (tested on [regextester.com](https://www.regextester.com/))

Thanks!

**Comment by scorpionknifes** [comment]
Hi there, the `pcre.MULTILINE` flag can only be used on the `Compile` functions. 

Try doing `pattern.MatchString(string, 0)` instead or check the flag list for more options https://github.com/scorpionknifes/go-pcre/blob/master/pcre.go#L18-L65

Thanks!

**Comment by dwisiswant0** [comment]
Thanks for your prompt response, @scorpionknifes! Now it works as expected.
